// ===========================================================================
// StoryDNA — loader + manifest merge
//
// StoryDNA is the per-story performance document generated by Gemini
// (src/scripts/generate-story-dna.js). It is the source of truth for
// beat-level performance: text, emotion, tension, voice direction,
// breathing, silence, sound priority, spatial direction, listener role,
// and choice moments.
//
// applyDNA() merges DNA beats over a beat-manifest chapter map by beat id,
// so BeatScheduler (the runtime source of truth) carries every DNA field
// on each beat it executes. Stories without DNA pass through unchanged.
// ===========================================================================

import dna10seconds from "../data/storyDNA/10seconds.json";

const STORY_DNA = {
  "10seconds": dna10seconds,
};

export function getStoryDNA(storyKey) {
  return STORY_DNA[storyKey] || null;
}

/** Merge DNA beat fields over manifest beats (matched by beat id). */
export function applyDNA(storyKey, chapterMap) {
  const dna = STORY_DNA[storyKey];
  if (!dna?.chapters) return chapterMap;

  const out = {};
  for (const [chIdx, chapter] of Object.entries(chapterMap)) {
    const dnaBeats = dna.chapters[chIdx]?.beats || [];
    const byId = Object.fromEntries(dnaBeats.map(b => [b.id, b]));
    out[chIdx] = {
      ...chapter,
      beats: (chapter.beats || []).map(beat => ({ ...beat, ...byId[beat.id] })),
    };
  }
  return out;
}

// DNA sfx name → asset file (only names that exist in /audio/v3/sfx/)
const SFX_FILES = {
  glass_break:     "/audio/sfx/glass_break.mp3",
  footsteps_stone: "/audio/sfx/footsteps_stone.mp3",
  floor_creak:     "/audio/sfx/floor_creak.mp3",
  door_handle:     "/audio/sfx/door_creak.mp3",
};

const SFX_VOLUMES = {
  glass_break: 0.6,
  footsteps_stone: 0.3,
  floor_creak: 0.2,
  door_handle: 0.45,
};

export function getBeatSfx(beat) {
  if (!beat?.sfx || !SFX_FILES[beat.sfx]) return null;
  return {
    file: SFX_FILES[beat.sfx],
    volume: SFX_VOLUMES[beat.sfx] ?? 0.3,
    spatial: beat.spatial || null,
  };
}
